[package]
name = "edsdk"
version = "0.1.0"
edition = "2024"
description = "EOS Digital Software Development Kit"

[dependencies]
num_enum = "0.7.4"
tokio = { version = "1.46.1", features = ["full"] }


# [build-dependencies]
# bindgen = "0.72.0"

[features]
uint32 = []
uint16 = []
