name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install LLVM & Clang
      run: sudo apt-get update && sudo apt-get install -y clang llvm-dev libclang-dev
    - name: Install OpenCV dependencies
      run: sudo apt-get update && sudo apt-get install -y libopencv-dev pkg-config
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    # - name: Run tests
    #   run: LD_LIBRARY_PATH=native cargo test --verbose
    - name: Lint
      run: cargo clippy -- -D warnings
